### ISSUE TITLE
Winning but not winning?

### ISSUE THREAD

**Issue by iangriggs** [kasperdoggames/crypto-jumper#1]
In some plays I've got to the winning bell but the 'you have won' message didn't appear.

Try to find steps to reproduce.

It's when I'm playing against myself on two browsers so the other player dies quickly.

From that point neither browser seems to receive the newGame event and gets stuck where the level stopped. One player standing near the bell and the other watching the ghost player walking into the bell.

**Comment by otaiga** [comment]
not been able to replicate this so far...

**Comment by iangriggs** [comment]
Might be relevant to finishing the game, reaching the bell, after the contract has deemed the game has timed-out (reaching the 60 sec mark)?

**Comment by otaiga** [comment]
This is now fixed with "no winners this time" message if all players die before end of game
